/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/charater1.glb -o ./src/Character.jsx 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import {useControls}from "leva"
export function Character(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/charater1.glb')
  const { actions } = useAnimations(animations, group)

   //GUI에 애니메이션 이름 표시 (4월 25일 추가함)
  const animationNames=Object.keys(actions);
  const {animationName}=useControls({
    animationName:{
      value:animationNames[0],
      option:animationNames
    }
  })
  console.log(animationNames);

  useEffect(()=>{
    const action=actions[animationName];
    action.reset().fadeIn(0.5).play();
    return ()=>{
      action.fadeOut(0.5);
    }
  },[animationName])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="charater" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig8Hips} />
          <skinnedMesh name="Ch07_Body001" geometry={nodes.Ch07_Body001.geometry} material={materials['Ch07_body.001']} skeleton={nodes.Ch07_Body001.skeleton} />
          <skinnedMesh name="Ch07_Eyelashes001" geometry={nodes.Ch07_Eyelashes001.geometry} material={materials['Ch07_hair.001']} skeleton={nodes.Ch07_Eyelashes001.skeleton} />
          <skinnedMesh name="Ch07_Hair001" geometry={nodes.Ch07_Hair001.geometry} material={materials['Ch07_hair.001']} skeleton={nodes.Ch07_Hair001.skeleton} />
          <skinnedMesh name="Ch07_Heels001" geometry={nodes.Ch07_Heels001.geometry} material={materials['Ch07_body.001']} skeleton={nodes.Ch07_Heels001.skeleton} />
          <skinnedMesh name="Ch07_Pants001" geometry={nodes.Ch07_Pants001.geometry} material={materials['Ch07_body.001']} skeleton={nodes.Ch07_Pants001.skeleton} />
          <skinnedMesh name="Ch07_Shirt001" geometry={nodes.Ch07_Shirt001.geometry} material={materials['Ch07_body.001']} skeleton={nodes.Ch07_Shirt001.skeleton} />
          <skinnedMesh name="Ch07_Suit001" geometry={nodes.Ch07_Suit001.geometry} material={materials['Ch07_body.001']} skeleton={nodes.Ch07_Suit001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/charater1.glb')
